-- Выполните этот SQL в Supabase: SQL Editor → New query → Run

CREATE TABLE IF NOT EXISTS burials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  location TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  description TEXT DEFAULT '',
  persons JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE burials ENABLE ROW LEVEL SECURITY;

-- Все посетители могут читать данные (карта)
CREATE POLICY "public_read_burials"
  ON burials FOR SELECT
  TO anon, authenticated
  USING (true);

-- Только вошедшие админы могут менять данные
CREATE POLICY "auth_insert_burials"
  ON burials FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "auth_update_burials"
  ON burials FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "auth_delete_burials"
  ON burials FOR DELETE
  TO authenticated
  USING (true);
